language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

sudo: required

env:
    global:
        - JOBS=4
    matrix:
        - CONFIGURE_ARGS='-Uusethreads'
        - CONFIGURE_ARGS='-Dusethreads'

matrix:
  exclude:
  - compiler: clang
    os: linux
  - compiler: gcc
    os: osx

script:
  - ./Configure -des -Dusedevel -Uversiononly -Dcc=$CC $CONFIGURE_ARGS -Dprefix=$HOME/perl-blead -DDEBUGGING && TEST_JOBS=$JOBS make -j$JOBS test_harness_notty && make -j$JOBS install && $HOME/perl-blead/bin/perlivp

addons:
    apt:
        packages:
            - file
            - cpio
            - libdb-dev
            - libgdbm-dev
            - zlib1g-dev
            - libbz2-dev
